version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache



workflows:
  main:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
