version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@0.0.10
  telegram: woltsu/telegram@0.0.9

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Test
          command: python manage.py run_test


workflows:
  main:
    jobs:
      - build
      - test
      - heroku/deploy-via-git:
          requires:
            - build
      - telegram/notify:
          requires:
            - heroku/deploy-via-git
          telegram-bot-token: TELEGRAM_BOT_TOKEN
          message: 'TaipeiWeather successfully deploy to Heroku!'